version: "3.1"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: fk
      POSTGRES_DB: fk
    ports:
      - 5432:5432

  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  toches:
    image: frikanalen/toches
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:fk@db/fk
      - FK_API_KEY=1234
    ports:
      - 8080:80

  mock-data:
    image: frikanalen/toches
    restart: on-failure
    environment:
      - DATABASE_URL=postgres://postgres:fk@db/fk
      - FK_API_KEY=1234
    command: ['sh', '-c', 'sleep 10s; yarn makeMockData']